version: "3.8"

services:
  web: &web
    tty: true
    stdin_open: true
    image: shortlink:dev
    build:
      context: .
    command: sh docker/start.sh
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    env_file:
      - web.env
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shortlink_dev
    ports:
      - "3306:3306"
    volumes:
      - ./db_volume/mysql_data:/var/lib/mysql
      - ./db_volume/mysql_config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
