version: "3.8"

services:
  web: &web
    tty: true
    stdin_open: true
    image: shortlink:dev
    build:
      context: .
    command: sh docker/start.sh
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    env_file:
      - web.env
    depends_on:
      - db

  db:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - ./db_volume/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
