default: &default
  adapter: postgresql
  charset: utf8
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 10).to_i %>
  username: root
  password: password
  host: localhost

development:
  <<: *default
  host: <%= ENV.fetch('DB_HOST') { '127.0.0.1' } %>
  database: <%= ENV.fetch('DB_NAME_DEV') { 'shortlink_test' } %>
  username: <%= ENV.fetch('DB_USERNAME') { 'root' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'password' } %>

test:
  <<: *default
  host: <%= ENV.fetch('DB_HOST') { '127.0.0.1' } %>
  database: <%= ENV.fetch('DB_NAME_DEV') { 'shortlink_prod' } %>
  username: <%= ENV.fetch('DB_USERNAME') { 'root' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'password' } %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
